server:
  port: 8084
spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://config-service:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: config-server
          uri: lb://config-server
          predicates:
            - Path=/config-server/**
          filters:
            - StripPrefix=1
        - id: demo1-service
          uri: lb://demo1-service
          predicates:
            - Path=/demo1-service/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    instance:
      prefer-ip-address: true
    fetch-registry: true
    register-with-eureka: true
